# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/ERN24004/Projects/PYNQ/03_Fir/Fir/Fir.srcs/sources_1/bd/Fir_filter/ip/Fir_filter_xbar_0/Fir_filter_xbar_0.xci
# IP: The module: 'Fir_filter_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/ERN24004/Projects/PYNQ/03_Fir/Fir/Fir.gen/sources_1/bd/Fir_filter/ip/Fir_filter_xbar_0/Fir_filter_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fir_filter_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/ERN24004/Projects/PYNQ/03_Fir/Fir/Fir.srcs/sources_1/bd/Fir_filter/ip/Fir_filter_xbar_0/Fir_filter_xbar_0.xci
# IP: The module: 'Fir_filter_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/ERN24004/Projects/PYNQ/03_Fir/Fir/Fir.gen/sources_1/bd/Fir_filter/ip/Fir_filter_xbar_0/Fir_filter_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fir_filter_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
